import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { UserProvider } from "./context/user";
import { RoleProvider } from "./context/role";
import MainLayout from "./MainLayout";

export const metadata: Metadata = {
  title: "Tax Refund",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <RoleProvider>
            <UserProvider>
              <MainLayout>{children}</MainLayout>
            </UserProvider>
          </RoleProvider>
        </Providers>
      </body>
    </html>
  );
}
